-- ============================================================================
-- SRD builtin seed (2/3): 11 base classes + 15 prestige classes.
-- `data` JSONB matches classDataSchema in src/lib/schemas/content.ts.
-- Spell slot tables and full per-level feature tables are added in the spell
-- seed pass; here each caster carries its casting type/ability, and features
-- list the signature mechanical entries. Idempotent.
-- ============================================================================

delete from classes where source = 'builtin';

-- ---- Base classes ----
insert into classes (source, name, slug, is_prestige, data) values
('builtin','Barbarian','barbarian',false,'{"hitDie":12,"babProgression":"good","fort":"good","ref":"poor","will":"poor","skillPointsPerLevel":4,"classSkills":["climb","craft","handle-animal","intimidate","jump","listen","ride","survival","swim"],"features":[{"name":"Rage","level":1,"hook":"rage"},{"name":"Fast Movement","level":1},{"name":"Uncanny Dodge","level":2},{"name":"Trap Sense","level":3},{"name":"Improved Uncanny Dodge","level":5}]}'),
('builtin','Bard','bard',false,'{"hitDie":6,"babProgression":"average","fort":"poor","ref":"good","will":"good","skillPointsPerLevel":6,"classSkills":["appraise","balance","bluff","climb","concentration","craft","decipher-script","diplomacy","disguise","escape-artist","gather-information","hide","jump","knowledge-arcana","knowledge-history","knowledge-local","knowledge-nature","knowledge-nobility","listen","move-silently","perform","profession","sense-motive","sleight-of-hand","spellcraft","swim","tumble","use-magic-device"],"spellcasting":{"type":"spontaneous","ability":"cha"},"features":[{"name":"Bardic Music","level":1,"hook":"bardic-music"},{"name":"Bardic Knowledge","level":1},{"name":"Countersong","level":1},{"name":"Inspire Courage","level":1}]}'),
('builtin','Cleric','cleric',false,'{"hitDie":8,"babProgression":"average","fort":"good","ref":"poor","will":"good","skillPointsPerLevel":2,"classSkills":["concentration","craft","diplomacy","heal","knowledge-arcana","knowledge-history","knowledge-planes","knowledge-religion","profession","spellcraft"],"spellcasting":{"type":"prepared","ability":"wis","domains":true},"features":[{"name":"Turn or Rebuke Undead","level":1,"hook":"turn-undead"},{"name":"Domains","level":1,"hook":"domains"},{"name":"Spontaneous Casting (cure/inflict)","level":1}]}'),
('builtin','Druid','druid',false,'{"hitDie":8,"babProgression":"average","fort":"good","ref":"poor","will":"good","skillPointsPerLevel":4,"classSkills":["concentration","craft","diplomacy","handle-animal","heal","knowledge-nature","listen","profession","ride","spellcraft","spot","survival","swim"],"spellcasting":{"type":"prepared","ability":"wis"},"features":[{"name":"Animal Companion","level":1},{"name":"Nature Sense","level":1},{"name":"Wild Empathy","level":1},{"name":"Woodland Stride","level":2},{"name":"Wild Shape","level":5,"hook":"wild-shape"}]}'),
('builtin','Fighter','fighter',false,'{"hitDie":10,"babProgression":"good","fort":"good","ref":"poor","will":"poor","skillPointsPerLevel":2,"classSkills":["climb","craft","handle-animal","intimidate","jump","ride","swim"],"features":[{"name":"Bonus Feat","level":1,"hook":"bonus-feat"},{"name":"Bonus Feat (every even level)","level":2,"hook":"bonus-feat"}]}'),
('builtin','Monk','monk',false,'{"hitDie":8,"babProgression":"average","fort":"good","ref":"good","will":"good","skillPointsPerLevel":4,"classSkills":["balance","climb","concentration","craft","diplomacy","escape-artist","hide","jump","knowledge-arcana","knowledge-religion","listen","move-silently","perform","profession","sense-motive","spot","swim","tumble"],"features":[{"name":"Flurry of Blows","level":1,"hook":"flurry"},{"name":"Unarmed Strike","level":1,"hook":"unarmed-strike"},{"name":"AC Bonus (Wis)","level":1,"hook":"monk-ac"},{"name":"Evasion","level":2},{"name":"Fast Movement","level":3},{"name":"Ki Strike","level":4}]}'),
('builtin','Paladin','paladin',false,'{"hitDie":10,"babProgression":"good","fort":"good","ref":"poor","will":"poor","skillPointsPerLevel":2,"classSkills":["concentration","craft","diplomacy","handle-animal","heal","knowledge-nobility","knowledge-religion","profession","ride","sense-motive"],"spellcasting":{"type":"prepared","ability":"wis"},"features":[{"name":"Smite Evil","level":1,"hook":"smite"},{"name":"Detect Evil","level":1},{"name":"Divine Grace","level":2,"hook":"divine-grace"},{"name":"Lay on Hands","level":2,"hook":"lay-on-hands"},{"name":"Aura of Courage","level":3},{"name":"Special Mount","level":5}]}'),
('builtin','Ranger','ranger',false,'{"hitDie":8,"babProgression":"good","fort":"good","ref":"good","will":"poor","skillPointsPerLevel":6,"classSkills":["climb","concentration","craft","handle-animal","heal","hide","jump","knowledge-dungeoneering","knowledge-geography","knowledge-nature","listen","move-silently","profession","ride","search","spot","survival","swim","use-rope"],"spellcasting":{"type":"prepared","ability":"wis"},"features":[{"name":"Favored Enemy","level":1,"hook":"favored-enemy"},{"name":"Track","level":1},{"name":"Wild Empathy","level":1},{"name":"Combat Style","level":2,"hook":"combat-style"},{"name":"Animal Companion","level":4},{"name":"Woodland Stride","level":7}]}'),
('builtin','Rogue','rogue',false,'{"hitDie":6,"babProgression":"average","fort":"poor","ref":"good","will":"poor","skillPointsPerLevel":8,"classSkills":["appraise","balance","bluff","climb","craft","decipher-script","diplomacy","disable-device","disguise","escape-artist","forgery","gather-information","hide","intimidate","jump","knowledge-local","listen","move-silently","open-lock","perform","profession","search","sense-motive","sleight-of-hand","spot","swim","tumble","use-magic-device","use-rope"],"features":[{"name":"Sneak Attack","level":1,"hook":"sneak-attack","value":"+1d6 per odd level"},{"name":"Trapfinding","level":1},{"name":"Evasion","level":2},{"name":"Trap Sense","level":3},{"name":"Uncanny Dodge","level":4},{"name":"Improved Uncanny Dodge","level":8},{"name":"Special Ability","level":10}]}'),
('builtin','Sorcerer','sorcerer',false,'{"hitDie":4,"babProgression":"poor","fort":"poor","ref":"poor","will":"good","skillPointsPerLevel":2,"classSkills":["bluff","concentration","craft","knowledge-arcana","profession","spellcraft"],"spellcasting":{"type":"spontaneous","ability":"cha"},"features":[{"name":"Summon Familiar","level":1,"hook":"familiar"}]}'),
('builtin','Wizard','wizard',false,'{"hitDie":4,"babProgression":"poor","fort":"poor","ref":"poor","will":"good","skillPointsPerLevel":2,"classSkills":["concentration","craft","decipher-script","knowledge-arcana","knowledge-architecture","knowledge-dungeoneering","knowledge-geography","knowledge-history","knowledge-local","knowledge-nature","knowledge-nobility","knowledge-planes","knowledge-religion","profession","spellcraft"],"spellcasting":{"type":"prepared","ability":"int"},"features":[{"name":"Summon Familiar","level":1,"hook":"familiar"},{"name":"Scribe Scroll","level":1,"hook":"bonus-feat"},{"name":"Bonus Feat","level":5,"hook":"bonus-feat"}]}');

-- ---- Prestige classes (progressions + descriptive prerequisites) ----
insert into classes (source, name, slug, is_prestige, data) values
('builtin','Arcane Archer','arcane-archer',true,'{"isPrestige":true,"hitDie":8,"babProgression":"good","fort":"good","ref":"good","will":"poor","skillPointsPerLevel":4,"classSkills":["craft","hide","listen","move-silently","ride","spot","survival","use-rope"],"prerequisites":["Race: elf or half-elf","BAB +6","Weapon Focus (longbow or shortbow)","Point Blank Shot","Precise Shot"],"features":[{"name":"Enhance Arrow","level":1,"hook":"enhance-arrow"},{"name":"Imbue Arrow","level":2},{"name":"Seeker Arrow","level":4},{"name":"Phase Arrow","level":6},{"name":"Hail of Arrows","level":8},{"name":"Arrow of Death","level":10}]}'),
('builtin','Arcane Trickster','arcane-trickster',true,'{"isPrestige":true,"hitDie":4,"babProgression":"poor","fort":"poor","ref":"good","will":"good","skillPointsPerLevel":4,"classSkills":["appraise","balance","bluff","climb","concentration","craft","decipher-script","diplomacy","disable-device","disguise","escape-artist","gather-information","hide","jump","knowledge-arcana","listen","move-silently","open-lock","search","sense-motive","sleight-of-hand","spellcraft","spot","swim","tumble","use-rope"],"prerequisites":["Alignment: any nonlawful","Sneak attack +2d6","Cast arcane 3rd-level spells","Decipher Script 7","Disable Device 7","Escape Artist 7","Knowledge (arcana) 4"],"spellcasting":{"type":"prepared","ability":"int"},"features":[{"name":"Ranged Legerdemain","level":1},{"name":"Sneak Attack +1d6 (odd levels)","level":2,"hook":"sneak-attack"},{"name":"Impromptu Sneak Attack","level":3}]}'),
('builtin','Archmage','archmage',true,'{"isPrestige":true,"hitDie":4,"babProgression":"poor","fort":"poor","ref":"poor","will":"good","skillPointsPerLevel":2,"classSkills":["concentration","craft","knowledge-arcana","knowledge-planes","profession","search","spellcraft"],"prerequisites":["Cast 7th-level arcane spells","Knowledge (arcana) 15","Spellcraft 15","Skill Focus (Spellcraft)","Two metamagic feats","Craft/Skill focus prerequisites"],"spellcasting":{"type":"prepared","ability":"int"},"features":[{"name":"High Arcana","level":1,"hook":"high-arcana"}]}'),
('builtin','Assassin','assassin',true,'{"isPrestige":true,"hitDie":6,"babProgression":"average","fort":"poor","ref":"good","will":"poor","skillPointsPerLevel":4,"classSkills":["balance","bluff","climb","craft","decipher-script","diplomacy","disable-device","disguise","escape-artist","forgery","gather-information","hide","intimidate","jump","listen","move-silently","open-lock","search","sense-motive","sleight-of-hand","spot","swim","tumble","use-magic-device","use-rope"],"prerequisites":["Alignment: any evil","Disguise 4","Hide 8","Move Silently 8","Kill someone for no other reason than to join"],"spellcasting":{"type":"spontaneous","ability":"int"},"features":[{"name":"Death Attack","level":1,"hook":"death-attack"},{"name":"Poison Use","level":1},{"name":"Sneak Attack +1d6","level":1,"hook":"sneak-attack"},{"name":"Uncanny Dodge","level":2}]}'),
('builtin','Blackguard','blackguard',true,'{"isPrestige":true,"hitDie":10,"babProgression":"good","fort":"good","ref":"poor","will":"poor","skillPointsPerLevel":2,"classSkills":["concentration","craft","diplomacy","disguise","handle-animal","heal","hide","intimidate","knowledge-religion","profession","ride"],"prerequisites":["Alignment: any evil","BAB +6","Hide 5","Knowledge (religion) 2","Cleave","Power Attack","Sneak Attack ability"],"spellcasting":{"type":"prepared","ability":"wis"},"features":[{"name":"Detect Good","level":1},{"name":"Smite Good","level":1,"hook":"smite"},{"name":"Dark Blessing","level":1},{"name":"Command Undead","level":3},{"name":"Fiendish Servant","level":5}]}'),
('builtin','Dragon Disciple','dragon-disciple',true,'{"isPrestige":true,"hitDie":12,"babProgression":"average","fort":"good","ref":"poor","will":"good","skillPointsPerLevel":2,"classSkills":["concentration","craft","diplomacy","escape-artist","gather-information","knowledge-arcana","listen","profession","search","spellcraft","spot"],"prerequisites":["Race: any nondragon","Knowledge (arcana) 8","Cast arcane spells without preparation","Ability to cast 1st-level arcane spells"],"features":[{"name":"Natural Armor Increase","level":1,"hook":"natural-armor"},{"name":"Ability Boost (Str)","level":2},{"name":"Breath Weapon","level":3},{"name":"Blindsense","level":5},{"name":"Dragon Apotheosis","level":10}]}'),
('builtin','Duelist','duelist',true,'{"isPrestige":true,"hitDie":10,"babProgression":"good","fort":"poor","ref":"good","will":"poor","skillPointsPerLevel":4,"classSkills":["balance","bluff","escape-artist","jump","listen","perform","sense-motive","spot","tumble"],"prerequisites":["BAB +6","Dodge","Mobility","Weapon Finesse","Tumble 5","Perform 3"],"features":[{"name":"Canny Defense (Int to AC)","level":1,"hook":"canny-defense"},{"name":"Improved Reaction","level":2},{"name":"Enhanced Mobility","level":3},{"name":"Grace","level":4},{"name":"Precise Strike","level":5}]}'),
('builtin','Dwarven Defender','dwarven-defender',true,'{"isPrestige":true,"hitDie":12,"babProgression":"good","fort":"good","ref":"poor","will":"good","skillPointsPerLevel":2,"classSkills":["craft","listen","spot"],"prerequisites":["Race: dwarf","Alignment: any lawful","BAB +7","Dodge","Endurance","Toughness"],"features":[{"name":"Defensive Stance","level":1,"hook":"defensive-stance"},{"name":"Uncanny Dodge","level":2},{"name":"Damage Reduction","level":6},{"name":"Mobile Defense","level":8}]}'),
('builtin','Eldritch Knight','eldritch-knight',true,'{"isPrestige":true,"hitDie":6,"babProgression":"good","fort":"good","ref":"poor","will":"poor","skillPointsPerLevel":2,"classSkills":["concentration","craft","decipher-script","jump","knowledge-arcana","knowledge-nobility","ride","sense-motive","spellcraft","swim"],"prerequisites":["Proficiency with all martial weapons","Cast 3rd-level arcane spells"],"spellcasting":{"type":"prepared","ability":"int"},"features":[{"name":"Bonus Feat","level":1,"hook":"bonus-feat"}]}'),
('builtin','Hierophant','hierophant',true,'{"isPrestige":true,"hitDie":8,"babProgression":"poor","fort":"good","ref":"poor","will":"good","skillPointsPerLevel":2,"classSkills":["concentration","craft","diplomacy","heal","knowledge-arcana","knowledge-nature","knowledge-religion","profession","spellcraft"],"prerequisites":["Cast 7th-level divine spells","Knowledge (religion) 15","One metamagic feat"],"spellcasting":{"type":"prepared","ability":"wis"},"features":[{"name":"Special Ability (choose)","level":1,"hook":"hierophant-ability"}]}'),
('builtin','Horizon Walker','horizon-walker',true,'{"isPrestige":true,"hitDie":8,"babProgression":"good","fort":"good","ref":"poor","will":"poor","skillPointsPerLevel":4,"classSkills":["balance","climb","diplomacy","hide","knowledge-geography","listen","move-silently","profession","ride","spot","survival","swim"],"prerequisites":["Endurance","Survival 8"],"features":[{"name":"Terrain Mastery","level":1,"hook":"terrain-mastery"}]}'),
('builtin','Loremaster','loremaster',true,'{"isPrestige":true,"hitDie":6,"babProgression":"poor","fort":"poor","ref":"poor","will":"good","skillPointsPerLevel":4,"classSkills":["appraise","concentration","craft","decipher-script","diplomacy","gather-information","handle-animal","heal","knowledge-arcana","knowledge-history","knowledge-nature","knowledge-religion","perform","profession","spellcraft"],"prerequisites":["Cast 3rd-level divine or arcane spells","Knowledge (any two) 10 ranks each","Three metamagic or item creation feats","Skill Focus in a Knowledge skill"],"spellcasting":{"type":"prepared","ability":"int"},"features":[{"name":"Secret (choose)","level":1,"hook":"loremaster-secret"},{"name":"Lore","level":1},{"name":"Bonus Language","level":4},{"name":"Greater Lore","level":6},{"name":"True Lore","level":10}]}'),
('builtin','Mystic Theurge','mystic-theurge',true,'{"isPrestige":true,"hitDie":4,"babProgression":"poor","fort":"poor","ref":"poor","will":"good","skillPointsPerLevel":2,"classSkills":["concentration","craft","knowledge-arcana","knowledge-religion","profession","sense-motive","spellcraft"],"prerequisites":["Knowledge (arcana) 6","Knowledge (religion) 6","Cast 2nd-level arcane spells","Cast 2nd-level divine spells"],"spellcasting":{"type":"prepared","ability":"int"},"features":[{"name":"Combined Spellcasting (arcane + divine advance)","level":1,"hook":"dual-casting"}]}'),
('builtin','Shadowdancer','shadowdancer',true,'{"isPrestige":true,"hitDie":8,"babProgression":"average","fort":"poor","ref":"good","will":"poor","skillPointsPerLevel":6,"classSkills":["balance","bluff","craft","decipher-script","diplomacy","disguise","escape-artist","hide","jump","listen","move-silently","perform","profession","search","sleight-of-hand","spot","tumble","use-rope"],"prerequisites":["Move Silently 8","Hide 10","Perform (dance) 5","Dodge","Mobility","Combat Reflexes"],"features":[{"name":"Hide in Plain Sight","level":1,"hook":"hips"},{"name":"Evasion","level":2},{"name":"Darkvision","level":2},{"name":"Shadow Illusion","level":3},{"name":"Summon Shadow","level":3},{"name":"Shadow Jump","level":4}]}'),
('builtin','Thaumaturgist','thaumaturgist',true,'{"isPrestige":true,"hitDie":4,"babProgression":"poor","fort":"poor","ref":"poor","will":"good","skillPointsPerLevel":2,"classSkills":["concentration","craft","diplomacy","knowledge-arcana","knowledge-planes","knowledge-religion","profession","spellcraft"],"prerequisites":["Cast lesser planar ally","Knowledge (the planes) 4","Spell Focus (conjuration)"],"spellcasting":{"type":"prepared","ability":"wis"},"features":[{"name":"Improved Ally","level":1},{"name":"Augment Summoning","level":2},{"name":"Contingent Conjuration","level":6},{"name":"Planar Cohort","level":10}]}');
